name: tutorial
version: 1.0.0
dependencies:
  angular: "1.0.0"
  web_components: ">=0.8.0 <0.9.0"
  browser: any
  http_server: ">=0.9.3 <0.10.0"
dev_dependencies:
  unittest: ">=0.11.0+5 <0.12.0"
  mock: ">=0.11.0+2 <0.12.0"
transformers:
- angular:
    html_files:
      - lib/component/recipe_book.html
      - lib/component/rating.html
      - lib/component/search_recipe.html
      - lib/component/view_recipe.html
